/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse200 struct {
	ConfigRequest *interface{} `json:"ConfigRequest,omitempty"`
	GetDeliveryInfoRequest *interface{} `json:"GetDeliveryInfoRequest,omitempty"`
	LatestFulfilledInvoiceRequest *interface{} `json:"LatestFulfilledInvoiceRequest,omitempty"`
	ListTopLevelPiesCategories *interface{} `json:"ListTopLevelPiesCategories,omitempty"`
	ShopperRequest *interface{} `json:"ShopperRequest,omitempty"`
	TrolleyRequest *interface{} `json:"TrolleyRequest,omitempty"`
}
