/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20029 struct {
	Order *interface{} `json:"Order,omitempty"`
	CanLeaveOrderUnattended bool `json:"CanLeaveOrderUnattended,omitempty"`
	ContainsAgeRestricted bool `json:"ContainsAgeRestricted,omitempty"`
	ContainsMarketAgeRestricted bool `json:"ContainsMarketAgeRestricted,omitempty"`
	ContainsFrozen bool `json:"ContainsFrozen,omitempty"`
	ContainsRestrictedBySignature bool `json:"ContainsRestrictedBySignature,omitempty"`
	ContainsRestrictedBySignatureAndPhotoId bool `json:"ContainsRestrictedBySignatureAndPhotoId,omitempty"`
	IsPushedToGtm bool `json:"IsPushedToGtm,omitempty"`
	IsPushedToDtm bool `json:"IsPushedToDtm,omitempty"`
	Store *interface{} `json:"Store,omitempty"`
}
