/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type UiFulfilmentBody struct {
	AddressId float64 `json:"addressId,omitempty"`
	FulfilmentMethod string `json:"fulfilmentMethod,omitempty"`
	TimeslotId float64 `json:"timeslotId,omitempty"`
	TradingAccount *interface{} `json:"tradingAccount,omitempty"`
	WindowDate string `json:"windowDate,omitempty"`
}
