/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20022 struct {
	IsSuccessful bool `json:"IsSuccessful,omitempty"`
	Message *interface{} `json:"Message,omitempty"`
	IsNonServiced bool `json:"IsNonServiced,omitempty"`
	MarketMessage *interface{} `json:"MarketMessage,omitempty"`
}
