/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20018 struct {
	ShouldShowCanLeaveUnattendedPreference bool `json:"ShouldShowCanLeaveUnattendedPreference,omitempty"`
	DeliveryInstructions string `json:"DeliveryInstructions,omitempty"`
	PickupInstructions string `json:"PickupInstructions,omitempty"`
	CanLeaveUnattended bool `json:"CanLeaveUnattended,omitempty"`
	RestrictedItemsRecipient string `json:"RestrictedItemsRecipient,omitempty"`
}
