/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20011 struct {
	Products []interface{} `json:"Products,omitempty"`
	Corrections *interface{} `json:"Corrections,omitempty"`
	SearchResultsCount float64 `json:"SearchResultsCount,omitempty"`
	VisualShoppingAisleResponse []Object `json:"VisualShoppingAisleResponse,omitempty"`
	Aggregations []interface{} `json:"Aggregations,omitempty"`
	HasTobaccoItems bool `json:"HasTobaccoItems,omitempty"`
	Passes *interface{} `json:"Passes,omitempty"`
	SuggestedTerm *interface{} `json:"SuggestedTerm,omitempty"`
	FacetFilters []Object `json:"FacetFilters,omitempty"`
}
