/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse2006 struct {
	Successful bool `json:"Successful,omitempty"`
	Error_ *interface{} `json:"Error,omitempty"`
	TokenValue string `json:"TokenValue,omitempty"`
	ErrorMessage *interface{} `json:"ErrorMessage,omitempty"`
}
