/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type LoginLoginwithcredentialBody struct {
	Email string `json:"Email,omitempty"`
	Password string `json:"Password,omitempty"`
	RememberMe bool `json:"RememberMe,omitempty"`
	LinkToken *interface{} `json:"LinkToken,omitempty"`
	UserIdFromAgent *interface{} `json:"UserIdFromAgent,omitempty"`
}
