/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20014 struct {
	Totals *interface{} `json:"Totals,omitempty"`
	DeliveryFee *interface{} `json:"DeliveryFee,omitempty"`
	PotentialOrderPromotions []interface{} `json:"PotentialOrderPromotions,omitempty"`
	Message *interface{} `json:"Message,omitempty"`
	TrolleyItemCount float64 `json:"TrolleyItemCount,omitempty"`
	TotalTrolleyItemQuantity float64 `json:"TotalTrolleyItemQuantity,omitempty"`
	TotalWowDeliveryTrolleyItemQuantity float64 `json:"TotalWowDeliveryTrolleyItemQuantity,omitempty"`
	UpdatedItems []interface{} `json:"UpdatedItems,omitempty"`
}
