/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse20023 struct {
	DeliveryMethod string `json:"DeliveryMethod,omitempty"`
	Address *interface{} `json:"Address,omitempty"`
	TrolleyTarget *interface{} `json:"TrolleyTarget,omitempty"`
	CurrentDateAtFulfilmentStore string `json:"CurrentDateAtFulfilmentStore,omitempty"`
	ReservedDate *interface{} `json:"ReservedDate,omitempty"`
	ReservedTime *interface{} `json:"ReservedTime,omitempty"`
	IsDeliveryPlusEligible bool `json:"IsDeliveryPlusEligible,omitempty"`
	DeliveryInstructions string `json:"DeliveryInstructions,omitempty"`
	PickupInstructions string `json:"PickupInstructions,omitempty"`
	IsNonServiced bool `json:"IsNonServiced,omitempty"`
	IsExpress bool `json:"IsExpress,omitempty"`
	IsSecondary bool `json:"IsSecondary,omitempty"`
	IsCrowdSourced bool `json:"IsCrowdSourced,omitempty"`
	CanLeaveUnattended bool `json:"CanLeaveUnattended,omitempty"`
	MarketDeliveryDetails *interface{} `json:"MarketDeliveryDetails,omitempty"`
	WindowFeeStructureId float64 `json:"WindowFeeStructureId,omitempty"`
}
