/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type SearchProductsBody struct {
	Filters []Object `json:"Filters,omitempty"`
	IsSpecial bool `json:"IsSpecial,omitempty"`
	Location string `json:"Location,omitempty"`
	PageNumber float64 `json:"PageNumber,omitempty"`
	PageSize float64 `json:"PageSize,omitempty"`
	SearchTerm string `json:"SearchTerm,omitempty"`
	SortType string `json:"SortType,omitempty"`
}
