/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse2003 struct {
	Title string `json:"Title,omitempty"`
	MetaDescription string `json:"MetaDescription,omitempty"`
	Groups []Object `json:"Groups,omitempty"`
}
