/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse2005 struct {
	FirstName string `json:"FirstName,omitempty"`
	LoginResult string `json:"LoginResult,omitempty"`
	AuthenticationErrorMessage *interface{} `json:"AuthenticationErrorMessage,omitempty"`
	LoginCollectionZoneMessages []Object `json:"LoginCollectionZoneMessages,omitempty"`
	PasswordResetToken *interface{} `json:"PasswordResetToken,omitempty"`
	HasCollectionZoneMessages bool `json:"HasCollectionZoneMessages,omitempty"`
	LoginViaAgent *interface{} `json:"LoginViaAgent,omitempty"`
	PreferredChannel float64 `json:"PreferredChannel,omitempty"`
	ValidPhone bool `json:"ValidPhone,omitempty"`
	OtpResult bool `json:"OtpResult,omitempty"`
	MaskedChannel string `json:"MaskedChannel,omitempty"`
}
