/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type DigitalPayPaymentBody struct {
	Payments []Object `json:"payments,omitempty"`
	AccountAmount float64 `json:"accountAmount,omitempty"`
	AccountPassword *interface{} `json:"accountPassword,omitempty"`
	OpenpayAmount float64 `json:"openpayAmount,omitempty"`
}
