/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type DeliveryOptionsBody struct {
	CanLeaveUnattended bool `json:"CanLeaveUnattended,omitempty"`
	DeliveryInstructions string `json:"DeliveryInstructions,omitempty"`
}
