/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type UiSeoMetatagsBody struct {
	FormatObject string `json:"FormatObject,omitempty"`
	IsSpecial bool `json:"IsSpecial,omitempty"`
	PageType string `json:"PageType,omitempty"`
	UrlPath string `json:"UrlPath,omitempty"`
}
