/*
 * flows_filtered Mitmproxy2Swagger
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: 1.0.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */
package woolworths

type InlineResponse2007 struct {
	OrderId *interface{} `json:"OrderId,omitempty"`
	AmendCutoffTime *interface{} `json:"AmendCutoffTime,omitempty"`
	IsAmendingMarketOrder bool `json:"IsAmendingMarketOrder,omitempty"`
}
